ui.base.url = https://automationexercise.com/
api.base.url = https://automationexercise.com/api

ui.report.path = ../automation-ui/target/allure-results
api.report.path = ../automation-api/target/allure-results
allure.report.path = ../reports

download.dir = assets/files
screenshot.dir = assets/images
video.dir = assets/videos

mongodb.connection.string = mongodb://localhost:27017
mongodb.database.name = automation

execution.recording.enabled = true

browser.gecko.driver = /snap/bin/geckodriver
browser.firefox.binary = /snap/firefox/current/usr/lib/firefox/firefox
